#!/usr/bin/env python3
"""Prepare an existing project for a full GenerateVeoPrompts regeneration.

This tool keeps the canonical data flow/schema unchanged. It deterministically
rebuilds the splitter-owned semantic alignment fields from the preserved
narration stream and invalidates every prompt-derived Veo field/artifact so a
regeneration cannot silently reuse stale data.

Rebuilt for every scene:
  context_ref, sentence_id, part
Invalidated for every scene (must be regenerated by the Veo skill):
  continuity_ref, shot_type, veo_prompt
Preserved exactly:
  scene, voiceover, sub, timeline

USAGE:
  python3 .agents/tools/veo_regeneration_prepare.py \
    --folder data/video_long/example --type long --lang vi

EXIT: 0 success, 1 validation mismatch, 2 input/system error.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import sys
from pathlib import Path
from typing import Dict, List, Tuple

import word_splitter as ws
from semantic_receipts import receipt_path, runtime_dir_for_folder

REGENERATED_ALIGNMENT_FIELDS = ("context_ref", "sentence_id", "part")
INVALIDATED_VISUAL_FIELDS = ("continuity_ref", "shot_type", "veo_prompt")
PRESERVED_FIELDS = ("scene", "voiceover", "sub", "timeline")


def fail(msg: str, code: int = 1) -> None:
    print(f"ERROR: {msg}", file=sys.stderr)
    raise SystemExit(code)


def load_json(path: Path):
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        fail(f"cannot read JSON {path}: {exc}", 2)


def hash_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def scene_stream(chapters: List[Tuple[Path, List[dict]]]) -> List[dict]:
    return [scene for _, rows in chapters for scene in rows]


def validate_current_sources(folder: Path, video_type: str, lang: str) -> List[Tuple[Path, List[dict]]]:
    master = folder / "master_script.txt"
    if not master.exists():
        fail(f"missing {master}", 2)

    paths = sorted(folder.glob("chapter_*.json"))
    if not paths:
        fail("no chapter_*.json files found", 2)

    chapters: List[Tuple[Path, List[dict]]] = []
    for path in paths:
        data = load_json(path)
        if not isinstance(data, list) or not data:
            fail(f"{path.name} must be a non-empty scene array")
        chapters.append((path, data))

    scenes = scene_stream(chapters)
    actual_nums = [s.get("scene") for s in scenes]
    expected_nums = list(range(1, len(scenes) + 1))
    if actual_nums != expected_nums:
        fail(f"scene numbering must be globally contiguous from 1; got {actual_nums[:12]}{'...' if len(actual_nums) > 12 else ''}")

    for path, rows in chapters:
        for idx, scene in enumerate(rows):
            n = scene.get("scene")
            vo = scene.get("voiceover")
            sub = scene.get("sub")
            if not isinstance(vo, str) or not vo.strip():
                fail(f"{path.name} scene {n}: voiceover must be non-empty")
            if not isinstance(sub, str) or not sub.strip():
                fail(f"{path.name} scene {n}: sub must be non-empty")
            wc = len(vo.split())
            if len(sub.split()) != wc:
                fail(f"{path.name} scene {n}: sub word count {len(sub.split())} != voiceover {wc}; refusing to regenerate around a broken narration/subtitle source")
            limit = ws.WORDS_PER_SCENE[(video_type, lang)]
            if wc < 1 or wc > limit:
                fail(f"{path.name} scene {n}: voiceover has {wc} words; allowed 1..{limit}")
            if idx < len(rows) - 1 and wc != limit:
                fail(f"{path.name} scene {n}: non-final chapter scene has {wc} words; expected exactly {limit}")

    master_tokens = master.read_text(encoding="utf-8").split()
    scene_tokens = [tok for s in scenes for tok in str(s["voiceover"]).split()]
    if master_tokens != scene_tokens:
        limit = min(len(master_tokens), len(scene_tokens))
        at = next((i for i in range(limit) if master_tokens[i] != scene_tokens[i]), limit)
        exp = master_tokens[at] if at < len(master_tokens) else "<END>"
        got = scene_tokens[at] if at < len(scene_tokens) else "<END>"
        fail(
            "refusing regeneration because current voiceover stream is not an exact whitespace-token split of master_script.txt: "
            f"master={len(master_tokens)}, scenes={len(scene_tokens)}, first divergence token {at+1}: expected {exp!r}, got {got!r}"
        )
    return chapters


def rebuild_in_memory(chapters: List[Tuple[Path, List[dict]]], video_type: str, lang: str) -> Dict[Path, List[dict]]:
    words_per_scene = ws.WORDS_PER_SCENE[(video_type, lang)]
    next_scene = 1
    next_sentence = 1
    outputs: Dict[Path, List[dict]] = {}

    for path, existing in chapters:
        # Because the global master-script coverage check already passed,
        # concatenating preserved voiceover reconstructs this chapter's exact
        # splitter input token stream without trusting old alignment metadata.
        chapter_text = " ".join(str(s["voiceover"]).strip() for s in existing)
        rebuilt, computed_next_scene, computed_next_sentence = ws.build_scenes(
            chapter_text,
            words_per_scene,
            scene_start=next_scene,
            sentence_start=next_sentence,
        )
        if len(rebuilt) != len(existing):
            fail(f"{path.name}: canonical re-split produced {len(rebuilt)} scenes, existing chapter has {len(existing)}; refusing destructive merge")

        merged: List[dict] = []
        for old, fresh in zip(existing, rebuilt):
            n = old.get("scene")
            if fresh["scene"] != n:
                fail(f"{path.name}: scene identity mismatch during rebuild ({n} != {fresh['scene']})")
            if fresh["voiceover"].split() != str(old.get("voiceover", "")).split():
                fail(f"{path.name} scene {n}: canonical splitter changed the voiceover boundary; refusing merge")

            # Preserve all canonical non-Veo source/downstream fields exactly,
            # overwrite the deterministic alignment trio, and delete every
            # prompt-derived field so stale values cannot be accidentally reused.
            row = dict(old)
            row["context_ref"] = fresh["context_ref"]
            row["sentence_id"] = fresh["sentence_id"]
            row["part"] = fresh["part"]
            for key in INVALIDATED_VISUAL_FIELDS:
                row.pop(key, None)
            merged.append(row)

        outputs[path] = merged
        next_scene = computed_next_scene
        next_sentence = computed_next_sentence

    return outputs


def atomic_write_json(path: Path, data) -> None:
    raw = (json.dumps(data, ensure_ascii=False, indent=2) + "\n").encode("utf-8")
    tmp = path.with_name(path.name + ".regen.tmp")
    tmp.write_bytes(raw)
    os.replace(tmp, path)


def invalidate_prompt_artifacts(folder: Path) -> List[Path]:
    removed: List[Path] = []
    runtime = runtime_dir_for_folder(folder)
    candidates = [
        runtime / f"_veo_progress_{folder.name}.json",
        receipt_path(folder),
        folder / "all_veo_prompt.json",
    ]
    for path in candidates:
        if path.exists():
            path.unlink()
            removed.append(path)
    return removed


def main() -> None:
    ap = argparse.ArgumentParser(description="Deterministically rebuild Veo scene alignment and invalidate all old prompt-derived state")
    ap.add_argument("--folder", required=True)
    ap.add_argument("--type", required=True, choices=["short", "long"])
    ap.add_argument("--lang", required=True, choices=["vi"])
    ap.add_argument("--dry-run", action="store_true", help="Validate/rebuild in memory but do not modify files")
    args = ap.parse_args()

    folder = Path(args.folder).resolve()
    if not folder.exists() or not folder.is_dir():
        fail(f"folder not found: {folder}", 2)

    chapters = validate_current_sources(folder, args.type, args.lang)
    rebuilt = rebuild_in_memory(chapters, args.type, args.lang)

    old_hashes = {p.name: hash_bytes(p.read_bytes()) for p, _ in chapters}
    changed_alignment = 0
    total = 0
    for path, old_rows in chapters:
        new_rows = rebuilt[path]
        for old, new in zip(old_rows, new_rows):
            total += 1
            if any(old.get(k) != new.get(k) for k in REGENERATED_ALIGNMENT_FIELDS):
                changed_alignment += 1

    if args.dry_run:
        print(f"DRY-RUN PASS: {total} scenes can be safely regenerated; {changed_alignment} scene(s) have alignment values that would change")
        return

    # All validation happens before the first mutation. Once here, each chapter
    # is atomically replaced, then every stale prompt-dependent artifact is deleted.
    for path, _ in chapters:
        atomic_write_json(path, rebuilt[path])
    removed = invalidate_prompt_artifacts(folder)

    print(f"VEO REGENERATION PREPARED: {total} scenes")
    print("REBUILT: context_ref, sentence_id, part")
    print("INVALIDATED: continuity_ref, shot_type, veo_prompt")
    print("PRESERVED: scene, voiceover, sub, timeline")
    print(f"ALIGNMENT CHANGED: {changed_alignment}/{total} scenes")
    if removed:
        print("REMOVED STALE ARTIFACTS: " + ", ".join(str(p) for p in removed))
    else:
        print("REMOVED STALE ARTIFACTS: none present")
    print("OLD CHAPTER SHA256: " + json.dumps(old_hashes, ensure_ascii=False, sort_keys=True))
    print("NEXT: regenerate continuity_ref + shot_type + veo_prompt from scene 1, then rerun deterministic and semantic micro-batch QA from scene 1.")


if __name__ == "__main__":
    main()
